services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    command:
      - /opt/mssql/bin/sqlservr
    volumes:
      - webrtcchatapp_sqlserver_data:/var/opt/mssql/data

  auth:
    build:
      context: ./AuthenticationService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=WebRTCChatDB;User Id=sa;Password=YourStrong!Passw0rd;Trusted_Connection=False;Encrypt=False;
    depends_on:
      - db

  # user:
  #   build:
  #     context: ./UserService
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development

  webrtc:
    build:
      context: ./WebRTCService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_URL=http://webrtc:8080/api
    depends_on:
      - db

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    environment:
      - API_URL=http://webrtc:8080/api
    depends_on:
      - webrtc

volumes:
  webrtcchatapp_sqlserver_data:
  data-protection:
